name: "Flutter Setup"
author: "Bancolombia"
description: "Flutter installer with caching support"
branding:
  icon: "package"
  color: "blue"

inputs:
  channel:
    description: "Flutter channel: stable | beta | dev"
    required: false
    default: "stable"
  flutter-version:
    description: 'Exact version (e.g. "3.32.0") or "latest" for the tip of the channel'
    required: false
    default: "latest"
  java-version:
    description: 'Temurin Java version (e.g. "17"). Empty to skip.'
    required: false
    default: "17"
  cache:
    description: "Enable caching for Flutter SDK and pub/Gradle packages"
    required: false
    default: "true"
  cache-key-suffix:
    description: "Optional suffix to manually invalidate caches"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Configurar Java (Temurin)
      if: ${{ inputs.java-version != '' }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Cache Gradle (opcional)
      if: ${{ inputs.cache == 'true' && hashFiles('**/*.gradle*','**/gradle-wrapper.properties','gradle/*.versions.toml','**/versions.properties','buildSrc/**/Versions.kt','buildSrc/**/Dependencies.kt') != '' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties','gradle/*.versions.toml','**/versions.properties','buildSrc/**/Versions.kt','buildSrc/**/Dependencies.kt') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Calculate cache keys and Flutter metadata
      id: meta
      shell: bash
      run: |
        echo "host=$(uname -s | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        echo "arch=$(uname -m)" >> "$GITHUB_OUTPUT"
        echo "channel=${{ inputs.channel }}" >> "$GITHUB_OUTPUT"
        echo "version=${{ inputs.flutter-version }}" >> "$GITHUB_OUTPUT"

    - name: Restore Flutter SDK cache
      if: ${{ inputs.cache == 'true' }}
      id: flutter-cache
      uses: actions/cache@v4
      with:
        path: ~/.flutter
        key: flutter-${{ steps.meta.outputs.host }}-${{ steps.meta.outputs.arch }}-${{ steps.meta.outputs.channel }}-${{ steps.meta.outputs.version }}-${{ inputs.cache-key-suffix }}

    - name: Install Flutter SDK (if not cached)
      if: ${{ steps.flutter-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -euxo pipefail
        mkdir -p "$RUNNER_TEMP"
        cd "$RUNNER_TEMP"

        # Clonar Flutter
        if [ "${{ inputs.flutter-version }}" = "latest" ]; then
          git clone --depth 1 --branch "${{ inputs.channel }}" https://github.com/flutter/flutter.git flutter
        else
          git clone --depth 1 https://github.com/flutter/flutter.git flutter
          cd flutter
          git fetch --depth 1 origin "refs/tags/${{ inputs.flutter-version }}:refs/tags/${{ inputs.flutter-version }}"
          git checkout "tags/${{ inputs.flutter-version }}"
          cd ..
        fi

        rm -rf "$HOME/.flutter"
        mv "$RUNNER_TEMP/flutter" "$HOME/.flutter"

    - name: Add Flutter and Dart to PATH
      shell: bash
      run: |
        echo "$HOME/.flutter/bin" >> "$GITHUB_PATH"
        echo "$HOME/.flutter/bin/cache/dart-sdk/bin" >> "$GITHUB_PATH"
        echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

    - name: Show flutter version
      shell: bash
      run: flutter --version    

    - name: Precache Flutter artifacts
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          flutter precache --no-ios
        else
          flutter precache
        fi

    - name: Restore pub package cache
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          ${{ env.PUB_CACHE }}
        key: pub-${{ steps.meta.outputs.host }}-${{ steps.meta.outputs.arch }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pub-${{ steps.meta.outputs.host }}-${{ steps.meta.outputs.arch }}-
